apiVersion: v2
name: postgres
description: A Helm chart for PostgreSQL database
type: application
version: 1.0.0
appVersion: "15"
maintainers:
  - name: DevOps Team
keywords:
  - postgres
  - postgresql
  - database
