{{- if .Values.catApi.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cat-api.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cat-api.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "cat-api.database.host" . | quote }}
  DB_PORT: {{ .Values.catApi.config.DB_PORT | quote }}
  DB_NAME: {{ .Values.catApi.config.DB_NAME | quote }}
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cat-api.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgres.config.POSTGRES_DB | quote }}
  PGDATA: {{ .Values.postgres.config.PGDATA | quote }}
{{- end }}
