{{- if .Values.catApi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cat-api.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cat-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.catApi.deployment.replicas }}
  {{- end }}
  strategy:
    {{- toYaml .Values.catApi.deployment.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "cat-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.catApi.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cat-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.catApi.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cat-api.serviceAccountName" . }}
      containers:
      - name: cat-api
        {{- with .Values.catApi.securityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        image: "{{ .Values.catApi.image.repository }}:{{ .Values.catApi.image.tag }}"
        imagePullPolicy: {{ .Values.catApi.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.catApi.service.targetPort }}
          protocol: TCP
        {{- if .Values.catApi.livenessProbe.enabled }}
        livenessProbe:
          {{- toYaml .Values.catApi.livenessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.catApi.readinessProbe.enabled }}
        readinessProbe:
          {{- toYaml .Values.catApi.readinessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.catApi.startupProbe.enabled }}
        startupProbe:
          {{- toYaml .Values.catApi.startupProbe | nindent 12 }}
        {{- end }}
        env:
          # Load from Secret
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: POSTGRES_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: POSTGRES_PASSWORD
          
          # Load from ConfigMap
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ include "cat-api.fullname" . }}-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ include "cat-api.fullname" . }}-config
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ include "cat-api.fullname" . }}-config
                key: DB_NAME
          
          # Construct DATABASE_URL
          - name: DATABASE_URL
            value: "postgresql+asyncpg://$(DB_USER):$(DB_PASS)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
        
        {{- with .Values.catApi.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
