{{- if .Values.catApi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cat-api.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cat-api.labels" . | nindent 4 }}
  {{- with .Values.catApi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.catApi.ingress.className }}
  ingressClassName: {{ .Values.catApi.ingress.className }}
  {{- end }}
  {{- with .Values.catApi.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.catApi.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "cat-api.fullname" $ }}
                port:
                  number: {{ $.Values.catApi.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
