{{- if .Values.catApi.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cat-api.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cat-api.labels" . | nindent 4 }}
  {{- with .Values.catApi.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.catApi.service.type }}
  ports:
    - port: {{ .Values.catApi.service.port }}
      targetPort: {{ .Values.catApi.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "cat-api.selectorLabels" . | nindent 4 }}
{{- end }}
